# Generated by Django 5.2.16 on 2026-07-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0003_remove_eventosarena_credencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ngrok', 'Ngrok'), ('cloudflare', 'Cloudflare'), ('other', 'Other')], default='ngrok', max_length=50)),
                ('instance', models.CharField(max_length=255, unique=True)),
                ('public_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='arena.arenaclient')),
            ],
        ),
    ]
