# Generated by Django 5.2.12 on 2026-06-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscricoeseventossge',
            table='sge_inscricoes_eventos_cbw',
        ),
        migrations.AlterModelTable(
            name='resultadosge',
            table='sge_resultados_arena',
        ),
    ]
