# Generated by Django 5.2.16 on 2026-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sge', '0002_alter_inscricoeseventossge_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSGE',
            fields=[
                ('pk', models.CompositePrimaryKey('ano', 'grupo', 'id_classe_peso', 'colocacao', 'id_atleta', blank=True, editable=False, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('grupo', models.TextField()),
                ('id_classe_peso', models.IntegerField()),
                ('colocacao', models.IntegerField()),
                ('nome_completo', models.TextField(blank=True, null=True)),
                ('estilo', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('peso', models.TextField(blank=True, null=True)),
                ('pontos', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('data_recorte', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('clube', models.TextField(blank=True, null=True)),
                ('clube_url_logo', models.TextField(blank=True, null=True)),
                ('fed_url_logo', models.TextField(blank=True, null=True)),
                ('federacao', models.TextField(blank=True, null=True)),
                ('federacao_uf', models.TextField(blank=True, null=True)),
                ('urlfotoatleta', models.TextField(blank=True, db_column='urlFotoAtleta', null=True)),
            ],
            options={
                'db_table': 'sge_ranking',
                'managed': False,
            },
        ),
    ]
