# Generated by Django 5.2.12 on 2026-05-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arena', '0002_arenaclient_arenafight_arenasession_and_more'),
        ('sge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_athlete', models.ManyToManyField(blank=True, related_name='atleta_arena_athlete_origin', to='arena.arenaathlete')),
                ('arena_custom_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atleta_arena_origin', to='arena.arenaperson')),
                ('arena_fighter', models.ManyToManyField(blank=True, related_name='atleta_arena_fighter_origin', to='arena.arenafighter')),
                ('sge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_atleta_sge_origin', to='sge.gestaoidsatletas')),
                ('sge_id_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleta_sge_origin', to='sge.gestaoatletas')),
            ],
        ),
        migrations.CreateModel(
            name='EventosMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_arena_origin', to='arena.arenasportevent')),
                ('sge_event', models.ManyToManyField(related_name='evento_sge_origin', to='sge.gestaoeventos')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaClientsMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_client_origin', to='arena.arenaclient')),
                ('eventos_match', models.ManyToManyField(blank=True, related_name='arena_client_eventos_match_origin', to='integration.eventosmatch')),
            ],
        ),
        migrations.CreateModel(
            name='LutaMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_fight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luta_arena_origin', to='arena.arenafight')),
                ('sge_luta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luta_sge_origin', to='sge.lutasge')),
            ],
        ),
    ]
