# Generated by Django 5.0 on 2026-05-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_safe_bridge_rename_stage1'),
        ('normalization', '0003_agegroupmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbridge',
            name='age_group_mappings',
            field=models.ManyToManyField(blank=True, help_text='Normalized age group mappings that this event bridge covers', related_name='event_bridges', to='normalization.agegroupmapping'),
        ),
        migrations.AlterField(
            model_name='eventbridge',
            name='age_group',
            field=models.CharField(blank=True, help_text='Legacy: Arena age group (use age_group_mappings instead)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventbridge',
            name='sge_age_category',
            field=models.CharField(blank=True, help_text='Legacy: SGE age category (use age_group_mappings instead)', max_length=255, null=True),
        ),
    ]
