# Generated by Django 5.2.12 on 2026-04-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsArena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=150, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=150, null=True)),
                ('api_key', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_maquina', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventosSge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sge', models.IntegerField(unique=True)),
                ('local', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('id_tipo', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('escopo', models.CharField(blank=True, max_length=50, null=True)),
                ('audienceName', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_categoria_arena', models.CharField(blank=True, max_length=150, null=True)),
                ('id_evento', models.IntegerField()),
                ('id_atleta1', models.IntegerField()),
                ('id_atleta2', models.IntegerField()),
                ('flag_finalizado', models.IntegerField()),
                ('round', models.CharField(max_length=150)),
                ('id_atleta_ganhador', models.IntegerField(blank=True, null=True)),
                ('sportAlternateName', models.CharField(max_length=150)),
                ('weightCategoryName', models.CharField(max_length=150)),
                ('audienceName', models.CharField(max_length=150)),
                ('id_classe_peso', models.IntegerField(blank=True, null=True)),
                ('atleta1_flag_injured', models.IntegerField(blank=True, null=True)),
                ('atleta1_flag_seeded', models.IntegerField(blank=True, null=True)),
                ('atleta1_draw_rank', models.CharField(blank=True, max_length=10, null=True)),
                ('atleta1_RobinRank', models.CharField(blank=True, max_length=10, null=True)),
                ('atleta2_flag_injured', models.IntegerField(blank=True, null=True)),
                ('atleta2_flag_seeded', models.IntegerField(blank=True, null=True)),
                ('atleta2_draw_rank', models.CharField(blank=True, max_length=10, null=True)),
                ('atleta2_RobinRank', models.CharField(blank=True, max_length=10, null=True)),
                ('resultado', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_vitoria', models.CharField(blank=True, max_length=10, null=True)),
                ('atleta1_ranking_point', models.IntegerField(blank=True, null=True)),
                ('atleta2_ranking_point', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('tapete', models.CharField(max_length=10)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('is_temporary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EventosArena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_arena', models.CharField(max_length=100, unique=True)),
                ('nome_evento', models.CharField(max_length=100)),
                ('isTeamEvent', models.BooleanField()),
                ('isBeachWrestlingTournament', models.BooleanField()),
                ('audienceName', models.CharField(blank=True, max_length=50, null=True)),
                ('credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='arena.credentialsarena')),
                ('eventos_sge', models.ManyToManyField(related_name='eventos_arena', to='arena.eventossge')),
            ],
        ),
    ]
