# Generated by Django 5.2.12 on 2026-05-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('grant_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArenaFight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fight_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArenaSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='WebhookPayload',
            new_name='ArenaWebhookPayload',
        ),
        migrations.CreateModel(
            name='ArenaFighter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fighter_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighters', to='arena.arenafight')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaAthlete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('athlete_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='arena.arenafighter')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='arena.arenaathlete')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaMat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mat_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mats', to='arena.arenasession')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaSportEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='arena.arenaclient')),
            ],
        ),
        migrations.AddField(
            model_name='arenasession',
            name='arena_sport_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='arena.arenasportevent'),
        ),
        migrations.CreateModel(
            name='ArenaSportEventWeightCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_sport_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_categories', to='arena.arenasportevent')),
            ],
        ),
        migrations.AddField(
            model_name='arenafight',
            name='arena_sport_event_weight_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='arena.arenasporteventweightcategory'),
        ),
        migrations.CreateModel(
            name='ArenaWebhook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webhook_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='arena.arenaclient')),
            ],
        ),
    ]
