# Generated by Django 5.2.12 on 2026-05-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_arenaclient_arenafight_arenasession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosarena',
            name='credencial',
        ),
        migrations.RemoveField(
            model_name='eventosarena',
            name='eventos_sge',
        ),
        migrations.DeleteModel(
            name='Luta',
        ),
        migrations.DeleteModel(
            name='CredentialsArena',
        ),
        migrations.DeleteModel(
            name='EventosArena',
        ),
        migrations.DeleteModel(
            name='EventosSge',
        ),
    ]
