# Generated by Django 5.2.16 on 2026-07-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_tunnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tunnel',
            old_name='instance_id',
            new_name='instance',
        ),
    ]
