# Generated by Django 5.2.12 on 2026-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdClassePeso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ano', models.TextField()),
                ('escopo', models.TextField()),
                ('estilo', models.TextField()),
                ('categoria', models.TextField()),
                ('id_classe_peso', models.IntegerField()),
                ('peso', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'id_classe_peso',
                'managed': False,
            },
        ),
    ]
