# Generated by Django 5.0 on 2026-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupNormal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age_group', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloNormal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estilo', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesoNormal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
