# Generated by Django 5.0 on 2026-05-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_agegroupnormal_estilonormal_pesonormal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(help_text="Normalized age group name (e.g., 'U17', 'Senior')", max_length=50, unique=True)),
                ('arena_variations', models.JSONField(default=list, help_text='List of Arena age group name variations')),
                ('sge_variation', models.CharField(help_text="SGE age category name (e.g., 'SUB 17', 'SENIOR')", max_length=50)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (youngest to oldest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Age Group Mapping',
                'verbose_name_plural': 'Age Group Mappings',
                'ordering': ['sort_order', 'canonical_name'],
            },
        ),
    ]
