# Generated by Django 5.0 on 2026-05-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0003_agegroupmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroupmapping',
            name='sge_variation',
        ),
        migrations.AddField(
            model_name='agegroupmapping',
            name='sge_variations',
            field=models.JSONField(default=list, help_text="List of SGE age category variations (first is primary, e.g., ['Sub-17', 'SUB 17'])"),
        ),
        migrations.AlterField(
            model_name='agegroupmapping',
            name='canonical_name',
            field=models.CharField(help_text="Normalized age group name based on Arena identifier (e.g., 'u17', 'seniors')", max_length=50, unique=True),
        ),
    ]
