# Generated by Django 5.2.12 on 2026-05-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0004_update_sge_variations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeGroupNormal',
        ),
        migrations.DeleteModel(
            name='EstiloNormal',
        ),
        migrations.DeleteModel(
            name='PesoNormal',
        ),
    ]
