# Generated by Django 5.2.12 on 2026-06-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0005_delete_agegroupnormal_delete_estilonormal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idclassepeso',
            table='sge_id_classe_peso',
        ),
    ]
