# Generated by Django 5.2.16 on 2026-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0006_alter_idclassepeso_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEstado',
            fields=[
                ('nome', models.TextField(primary_key=True, serialize=False)),
                ('pagina_atual', models.IntegerField()),
                ('total_paginas', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('indice_peso_atual', models.IntegerField(blank=True, null=True)),
                ('total_pesos', models.IntegerField(blank=True, null=True)),
                ('ano_atual', models.IntegerField(blank=True, null=True)),
                ('grupo_atual', models.TextField(blank=True, null=True)),
                ('id_classe_peso_atual', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_estado',
                'managed': False,
            },
        ),
    ]
